### ISSUE TITLE
Webhook not working

### ISSUE THREAD

**Issue by Data-Monkey** [Data-Monkey/Pi.Alert#3]
Webhook still not being sent.

```
pialert    | Traceback (most recent call last):
pialert    |   File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
pialert    |     return _run_code(code, main_globals, None,
pialert    |   File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
pialert    |     exec(code, run_globals)
pialert    |   File "/home/pi/pialert/pialert/__main__.py", line 314, in <module>
pialert    |     sys.exit(main())
pialert    |   File "/home/pi/pialert/pialert/__main__.py", line 276, in main
pialert    |     send_notifications(db)
pialert    |   File "/home/pi/pialert/pialert/reporting.py", line 288, in send_notifications
pialert    |     send_webhook (msg)
pialert    |   File "/home/pi/pialert/pialert/publishers/webhook.py", line 54, in send
pialert    |     mylog('debug', '[send_webhook] curlParams: '+  curlParams)
pialert    | TypeError: can only concatenate str (not "list") to str
```
```
+ should be probably changed to ,
```

**Comment by Data-Monkey** [comment]
changed to this:
```python
    try:
        # try runnning a subprocess
        mylog('debug', ['[send_webhook] curlParams: ', curlParams])
        p = subprocess.Popen(curlParams, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
```

**Comment by jokob-sk** [comment]
Webhook seems to be working 👍
